In [2]:
# Q1>
# There is a difference in the data type of variables list_ and array_list.

# The variable list_ is a Python list, whereas array_list is a numpy array.

# You can print the data types of both variables using the type() function.

import numpy as np

list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [3]:
# Q2>
import numpy as np

list_ = [ '1', '2', '3', '4', '5' ]
array_list = np.array(object = list_)
for element in list_:
    print(type(element))
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
# Q3>
# Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list
# This change will convert the elements in list_ from strings to integers because we have specified the data type as int using the dtype parameter.
# To print the data types of each and every element present in both the variables, list_ and array_list

In [5]:
# Q4>
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
# Q5>
import numpy as np

zeros_array = np.zeros((3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# Q6>
import numpy as np

identity_array = np.identity(5)

print(identity_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
